version: "3.3"
services:
  mysql_db:
    image: mysql:5.7
    container_name: mediscreen_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: mediscreen
      MYSQL_USER: allan
      MYSQL_PASSWORD: password
    networks:
    - mediscreen
    ports:
    - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - "./mediscreenPatient/doc/mediscreen_database.sql:/docker-entrypoint-initdb.d/1.sql"
    - "./mediscreenPatient/doc/mediscreen_test_data.sql:/docker-entrypoint-initdb.d/2.sql"


  mediscreen_patient:
    container_name: mediscreen_patient
    build: ./mediscreenPatient/.
    image: mediscreen-patient:0.0.1
    restart: unless-stopped
    ports:
    - "7078:8081"
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: mediscreen
      MYSQL_USER: allan
      MYSQL_PASSWORD: password
    depends_on:
    - mysql_db
    networks:
    - mediscreen


  mongo:
    image: mongo:latest
    ports:
    - '27017:27017'
    container_name: mongo
    restart: unless-stopped
    networks:
    - mediscreen
    volumes:
    - ./mediscreenNotes/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro


  mediscreen_notes:
    container_name: mediscreen_notes
    build: ./mediscreenNotes/.
    image: mediscreen-notes:0.0.1
    restart: unless-stopped
    ports:
    - "7079:8082"
    environment:
      NOSQL_HOST: host.docker.internal
      NOSQL_PORT: 27017
      NOSQL_DB_NAME: mediscreen

    depends_on:
    - mongo
    networks:
    - mediscreen


  mediscreen_diabet:
    container_name: mediscreen_diabet
    build: ./mediscreenDiabet/.
    image: mediscreen-diabet:0.0.1
    restart: unless-stopped
    ports:
    - "7080:8080"
    environment:
      FEIGN_PATIENT_NAME: mediscreenPatient
      FEIGN_PATIENT_URL: localhost:7078
      FEIGN_NOTES_NAME: mediscreenNotes
      FEIGN_NOTES_URL: localhost:7079


    depends_on:
    - mediscreen_patient
    - mediscreen_notes
    networks:
    - mediscreen


networks:
  mediscreen:
    driver: bridge


